# Generated by Django 3.2.9 on 2021-12-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default=0, max_length=255, verbose_name='size'),
            preserve_default=False,
        ),
    ]
